blueprint:
  name: WebOS Button Screen Off
  description: Turn off screen of webos device
  domain: automation
  source_url: https://github.com/DjordjeMandic/homeassistant-blueprints/blueprints/automation/webos/button_screenoff/webos_button_screenoff.yaml
  input:
    webos_media_player_entity:
      name: WebOS Media Player
      description: This is the media player of WebOS device that will be controlled
      selector:
        entity:
          domain: media_player
    button_entity:
      name: Button
      description: Button that will be used to turn screen off
      selector:
        entity:
          domain: input_button
mode: single
trigger:
  platform: state
  entity_id: !input button_entity
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input webos_media_player_entity
        state: "off"
      - condition: state
        entity_id: !input webos_media_player_entity
        state: unavailable
action:
  - service: webostv.command
    data:
      entity_id: !input webos_media_player_entity
      command: com.webos.service.tvpower/power/turnOffScreen
